### ISSUE TITLE
When following the console, scroll to bottom on each refresh

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#104]
When I start a task and then click "Follow console", the page will refresh every five seconds as expected. But if a bunch of console lines are added then I have to scroll down to the bottom of the page to see them. I would prefer the scrolling to be automatic, which matches the behaviour of Travis and GitHub Actions.

Maybe this could be implemented with a simple anchor at the bottom of the page, or maybe with a bit of JavaScript.

**Comment by lmcmicu** [comment]
We had been using an anchor in the original javascript-less solution, but you commented that the effect was too jarring (see https://github.com/ontodev/droid/issues/58#issuecomment-726188961), so we changed to using javascript without automatic scrolling.

I guess it might be less jarring if we scroll to the bottom using javascript rather than a meta tag? Intuitively, though, my sense is that if the old way was jarring this will be too.
