### ISSUE TITLE
DROID should not append .git-credentials to .gitignore if its already in there

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#54]
Otherwise we get spurious diffs.

**Comment by jamesaoverton** [comment]
Thanks. This should be fixed by 9b8d7c0c1ce4032ae78e48926173b56b155ff18c.

**Comment by matentzn** [comment]
This is still happening; maybe an update issue on ontodev.

**Comment by jamesaoverton** [comment]
I may have forgotten to rebuild and restart the server. I did that now. If you still see the problem, please reopen this issue.

**Comment by jamesaoverton** [comment]
My "fix" caused an error when checking out a new branch, so I reverted it and I'll reopen this.

**Comment by lmcmicu** [comment]
I don't understand how @jamesaoverton 's change could possibly have created a problem. Also I tested it out and didn't see any errors. Could you clarify what the problem was?

That said, `.gitignore` is actually written with that `.git-credentials` line in *two* different places in DROID, but in James' change he only prevented the duplicate write in one of those places. Could that have been the problem?

I'm going to add James' change back, _and_ also add a similar change in the other spot.

**Comment by lmcmicu** [comment]
Here is the new commit: https://github.com/ontodev/droid/commit/3b6ae8d463b3c37d4338024f131fd6c5353bbad8 Note the two places where `.gitignore` is written, in `checkout-remote-branch-to-local` and `create-local-branch`. In James' original commit the check was only being done in the first location.

I want to use the https://github.com/ontodev/droid/compare/misc-improvements branch to resolve a few other issues besides this one, so if any problems result from this change, we should (hopefully) see them.

**Comment by jamesaoverton** [comment]
I think it was failing when there was no `.git-credentials` file to begin with, but I can't quite remember.

**Comment by lmcmicu** [comment]
I found what was likely the issue that James was running into. The grep fails when `.gitignore` does not exist. Should be a quick fix. Reopening
