### ISSUE TITLE
When viewing a file, there's no link back to DROID

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#56]
We discussed that for now, opening the tree view in a new tab should be fine.

**Comment by jamesaoverton** [comment]
I've thought about this a lot, and decided that links to pages that DROID does not itself generate should open in new tabs.

(I partially implemented this, but when a view has to be rebuilt then the behaviour still needs improvment.)

The main alternatives are:

1. the browser's Back button; but with our CGI tree views you might have to click "Back" dozens of times
2. wrap the page in an HTML frame, with a DROID banner above; frames are the worst part of the 1990s web, have weird behaviour, were badly abused, and now have severe security restrictions
3. inject a DROID banner into the page content; this could easily mess up HTML+CSS layouts

I have a general principle that we should assume that users know how to use their browsers, and we should not override default browser behaviour. But I think we have to make an exception in this case, because the alternatives are too ugly.

**Comment by matentzn** [comment]
Happy with the simplest solution! New tab sounds fine!

**Comment by jamesaoverton** [comment]
The current behaviour for new tabs is:

- Make tasks: open in same tab
- External links: open in new tab
- Links to files: open in new tab
- Links to CGI scripts: open in new tab

This isn't always great. I created issue #65. I'm also worried about browsers blocking popup windows -- this should only be a problem for external links, but I'm not sure.

**Comment by jamesaoverton** [comment]
This has been addressed by opening stuff in new tabs, and also by #76. It's still not perfect but let's use new issues.
