### ISSUE TITLE
User feedback: "Pressing refresh is 'a bit annoying' " 

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#58]
Maybe we can make it possible to periodically refresh the view for long running tasks.

**Comment by jamesaoverton** [comment]
Yes, I'd really like this enhancement.

I like the Travis behaviour, but the details are pretty fancy.

The simpler server-side approach would be something like a "Follow" button (checkbox? play / pause?) that uses something like `<meta http-equiv='refresh' content='5; /ONTIE/branches/${BRANCH}#bottom'/>` and an anchor at the bottom of the page. I'd like to try this first.

The fancier client-side approach is to update the console without reloading the page.

**Comment by matentzn** [comment]
All of these sound great to me! We can probably try the simple first?

**Comment by jamesaoverton** [comment]
Even fancier, we could consider sending a browser notification when a long-running task finishes:

https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API

**Comment by matentzn** [comment]
That would be very cool as well, if there is a standard way to do it across browsers. But in my experience, being able to see that _something_ is happening (by a growing log) is  probably more important to convince the user that everything is in order - especially if the process runs for a very long time.

Eventually we will also have to think about what happens with super large log files - but we can make a ticket for that when  the time comes.

**Comment by lmcmicu** [comment]
<s>One thing we should keep in mind when implementing the solution to this is that now that we have changed the view-rebuild process to use multiple tabs (see https://github.com/ontodev/droid/issues/65), the following situation might occur:

1. User clicks on a view that is out of date, which DROID opens in another tab ("tab 2"), and the user confirms that she wants to rebuild it.
2. While the view is rebuilding, the user switches to the original tab and for whatever reason decides to launch another process, which kills the view rebuild before launching.

The result is that "tab 2" no longer shows the process that is rebuilding the view in the console, but the new process kicked off in step 2.

Right now we are displaying a warning banner in the first tab after the process gets killed to let the user know that they should close the second tab. This is less than ideal but it helps to avoid a bit of confusion.

With the automatic refresh that we're implementing as part of this issue, we have an opportunity to do something smarter to deal with this issue. This comment, then, is just a reminder to do that.</s>

Removing this last comment as it belongs more appropriately in its own issue.

**Comment by jamesaoverton** [comment]
PR #71 implements the basic refresh option, exactly as I asked for it. But now that I've tried it out, I don't like it. The page refresh is too jarring.

Now I think that the "Follow Console" button should trigger a little bit of JavaScript on a timer to fetch the console contents and update that element. (Since this feature is only for humans users, I don't mind a bit of JavaScript. Machines can just refresh the page.)

@lmcmicu What do you think?

**Comment by lmcmicu** [comment]
Yes I think it should be doable. I'll need to do a bit of investigation to be sure, but I think having an endpoint to directly access the console text, and then some javascript to repeatedly hit that endpoint (as @jamesaoverton suggested) will probably work and (hopefully) be relatively simple to implement.

**Comment by lmcmicu** [comment]
A couple of further notes:
* [This commit](https://github.com/ontodev/droid/pull/71/commits/ebe205f9e8956916bfdf26444190260b0dcca8dd) will have to be carefully rolled back
* It is actually a bit more complicated than simply reading the console output with some javascript code. This is due to the fact that the server colourises the console before rendering it. So either we will need to do the colouring in the javascript (probably less than ideal), or have the server prepare the colourised output first, somehow, for the javascript code to read.

**Comment by jamesaoverton** [comment]
Colours for the console are important. I’d rather handle the ANSI to HTML server-side. So an endpoint fir fetching the console content in HTML (not just text) would be good.
