### ISSUE TITLE
Super minor: DROID creates remote branches, but deletes only local

### ISSUE THREAD

**Issue by matentzn** [ontodev/droid#62]
It is a bit strange that when  I create a new branch in DROID, it creates a remote version as well; then, when I want to delete it, I cant without leaving DROID and deleting directly on Github. Just a side note, not really important.

**Comment by jamesaoverton** [comment]
@lmcmicu I think this goes together well with my proposal on #50. Let's consider adding (another) checkbox below "Are you sure you want to delete the branch foo?" saying: "Delete this branch from GitHub" (or something)

I'm not sure whether it should be checked by default.

**Comment by lmcmicu** [comment]
In an older version of DROID we were deleting remote branches without asking. That was changed to the current behaviour which is such that we never delete. Given that the latter was an explicit choice that was made, it seems to make sense to not check that checkbox by default. That choice was made a long time ago, though, and things may have changed since then. I guess the question now is just: how do we expect people to be normally using the tool?

**Comment by jamesaoverton** [comment]
Ok. Let's provide the checkbox for deleting the remote branch, but leave it unchecked by default.

I tend to just leave branches open after merging PRs, then go through and clean stale branches up every so often. Some people like to delete branches immediately after merging PRs. If we want to change the default behaviour later, that's fine.

The key benefit of this feature will be making it more clear that DROID is or is not deleting the remote branch.
