### ISSUE TITLE
Revise how "rebuild" works

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#65]
I changed DROID to open files in new tabs: https://github.com/ontodev/droid/issues/56#issuecomment-703111466 The key advantage is that the user can just close the tab and get back to DROID.

But this isn't working properly when DROID wants to rebuild a page. You click "Rebuild the view", it works, then you have to click the link to the file again, and it opens in another new tab (a third tab). Ignoring the tab problem, after using DROID for a while I find it annoying to wait for the rebuild and then click the file link again.

So I would like some changes:

- the user clicks a link to a file and DROID opens a new tab for the view (current behaviour, no change)
- if a rebuild is required, the page should show just the header and rebuild dialogue, not the rest of the Workflow and Version Control; then
    - "Do nothing" should close the tab
    - "Rebuild the view" should show just the Console in the current tab
        - when the user refreshes and the job is still running or has failed, they should see the updated Console
        - when the user refreshes and the job has succeeded, they should be redirected to the file view (in the current tab)
        - if the use clicks Cancel, the job should be cancelled and the tab closed
    - view stale should open the file in the current tab

**Comment by lmcmicu** [comment]
I am worried about these two requirements:

- "Do nothing" should close the tab
- "if the use clicks Cancel, the job should be cancelled and the tab closed".

I believe that this would have to be done in Javascript, but aren't there legitimate security reasons for not allowing a script to close a user's tab/window? I know there are ways around this; in particular it is considered "ok" for a javascript to close a window that it opened itself. But given that a good amount of time may have passed between starting a job and hitting Cancel, I am still worried about it.

Even more fundamentally, though, I thought  that part of the philosophy behind DROID was to use as little javascript as possible. Because if we are going to use javascript anyway then there are libraries we could use to do this more properly. For example, we could use Bootbox: http://bootboxjs.com/. Or we could also use bootstrap modals.

This begins to get pretty heavy-duty, though, which is why, if we want to preserve the current design philosophy I actually think it would be better to just render a blank page with a simple dialog that has no buttons or controls, just a message telling the user that there is nothing left to do on this tab and that she should close it.

**Comment by lmcmicu** [comment]
There is also an extra complication that's not indicated here, i.e., if there is already a process running on the branch when a user requests to see a view. In that case the user is first asked if (s)he wants to kill that process before being asked whether (s)he wants to rebuild the view. Given that I propose modifying this requirement:

"if a rebuild is required, the page should show just the header and rebuild dialogue, not the rest of the Workflow and Version Control;"

to

"if a rebuild is required, the page should show just the header and rebuild dialogue, not the rest of the Workflow, Version Control, or Console; while if killing a running process is required, the page should show the header and rebuild dialogue and Console, but not the Workflow and Version Control"

the reason being that the user should have some information (provided by the console) about the process (s)he is being asked to kill (or not).

**Comment by lmcmicu** [comment]
edited my previous comment

**Comment by lmcmicu** [comment]
now I edited my first comment.

**Comment by lmcmicu** [comment]
I previously wrote:

> I am worried about these two requirements:
> 
>     * "Do nothing" should close the tab
> 
>     * "if the use clicks Cancel, the job should be cancelled and the tab closed".
> 
> 

After chatting with @jamesaoverton about this, the solution decided on is to render a "blank" page with nothing but a message instructing the user that (s)he should close the tab. **In addition** the page will include a `<script>window.close();</script>` element in the header which will close the tab automatically in the case where the browser has javascript enabled. In the case where it is not enabled, then the user can simply close the tab on her own.
