### ISSUE TITLE
Better handling of HTML and HTML fragments for CGI scripts

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#76]
DROID currently handles CGI output like this:

1. if the CGI script output starts with an HTTP header:
    A. if the header has a Content-Type = text/html: insert the response HTML into DROID's HTML (with style, navbar, etc.) and respond with that
    B. otherwise return the output as an HTTP response
2. otherwise print the output to the console

See https://github.com/ontodev/droid/blob/master/src/droid/html.clj#L451

I'd like to change the behaviour of 1A. If the output is a full HTML document, that should be the response, without wrapping it in DROID's HTML. Now that we open CGI stuff in a new tab, we don't need to wrap the output in DROID's HTML.

The thing I'm worried about is that we might sometimes want the CGI script's HTML output to be wrapped with DROID's HTML. The benefit would be to share DROID's navbar and styling. I see two options:

1. The CGI script should return an HTML fragment and a special Content-Type, and DROID would wrap it. I couldn't find a standard for this, but maybe "text/html; fragment" would be OK.
2. DROID could set an environment variable with its HTML template, and the CGI script would either use it or not. In either case DROID would just return whatever it gets from the CGI script. This seems a little expensive if the CGI script will just ignore it.

In either case, the CGI script is more aware of DROID than I like.

Does anyone have use cases where we would want the CGI script to return just a fragment?

**Comment by lmcmicu** [comment]
I'm not sure I'd agree that the script needs to be aware of DROID per se. In case 1 the script needs to be aware that it is sending back its HTML to _someone_, but that could be anyone. In case 2 it needs to be aware that someone has sent it a template, but it needn't care who that was.

All else equal I prefer 1, partly for the reason that @jamesaoverton mentions (i.e., 2 is unnecessarily expensive), but mostly since this ultimately leaves all rendering control in DROID's hands. 

The only reason I can see for wanting to go with 2 is if we want scripts to be able to customise and/or tweak DROID's HTML. If that is an important use case, then 2 is the only option, although personally I don't love the idea of scripts having the ability to render a header that looks almost like DROID's but not quite.

From a coding point of view, 1 is easiest (it involves changing just one line of code, I think), but 2 is not that much harder.

**Comment by jamesaoverton** [comment]
Ok. Let's go with solution 1.

One more detail: I think that when DROID calls the CGI script, it should set the `Accept` header so that a CGI script can see the options:

```
Accept: text/plain, text/html, text/html-fragment, */*
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept

**Comment by lmcmicu** [comment]
@jamesaoverton I'm a bit confused. Is it `text/html; fragment` or `text/html-fragment`?

**Comment by lmcmicu** [comment]
Also, currently DROID is setting the `HTTP_ACCEPT` environment variable to the CGI script to just be whatever it gets from the incoming request. Can you clarify whether we should override this header with _only_ the values above, or should we just make sure that those values are in there?

No rush to reply.

**Comment by jamesaoverton** [comment]
I had been thinking `text/html; fragment`, which I couple examples of in the wild. But then I realized that the semicolon might interfere with how Accept header `;q=` "q-factor weighting" works. So now I think that `text/html-fragment` is better. I can't believe there isn't a standard for this.

Yes, DROID would change the Accept header before passing it on. When it sees `text/html` in the Accept header it should add the `text/html-fragment` to the beginning of the accept string, I think. So in that case: HTTP_ACCEPT = "text/html-fragment, " + incoming accept header.

Now my main worry is that the CGI script wants to include a `style` or `link` to CSS that should go in the page header instead of the body of the page. We use some custom styling for Gizmos trees already. I guess the fragment could include both a `head` and `body`, and DROID would parse them out and put them in place, but that would be a lot more work than just inserting an HTML fragment.
