### ISSUE TITLE
Implement configurable override for Makefile path

### ISSUE THREAD

**Issue by jamesaoverton** [ontodev/droid#85]
Coming out of the general discussion in #46, @matentzn and I agreed on one specific new DROID feature to implement now: We would like a configuration option `:makefile-path` at the project level to provide a relative path to a Makefile inside the branch. The default will be the top-level Makefile for the branch, which is the current behaviour. This Makefile should be used to read the Workflow section and to run Make tasks from that Makefile from that directory.

For example:

```
"ZECO"
{:project-title "Zebrafish Experimental Conditions Ontology"
 :project-welcome "welcome message"
 :project-description "description"
 :github-coordinates "jamesaoverton/zebrafish-experimental-conditions-ontology"
 :makefile-path "src/ontology/Makefile"
 :docker-config
 {:active? true
  :image "obolibrary/odkfull"
  :workspace-dir "/workspace/"
  :temp-dir "/tmp/droid/"
  :default-working-dir "/workspace/"
  :shell-command "bash"
  :env {"ENV_VAR_1" "env_var_1_value"}}} 
```

**Comment by matentzn** [comment]
Awesome you are looking into that! Note that the working directory for running make commands also get shifted to the location where the Makefile is: so if you have a `src/ontology/Makefile`, run `make` will necessitate to

```
cd src/ontology
make release
```

and not

```
make -f src/ontology/Makefile release
```

**Comment by jamesaoverton** [comment]
That's what I had in mind -- thanks for clarifying! I updated the issue.

**Comment by lmcmicu** [comment]
Can we assume that the name will always be 'Makefile' or do we need to be able to handle arbitrary names?

**Comment by matentzn** [comment]
There are some cases where I have multiple makefiles in the same directory (called then `mondo.Makefile` or similar) - I would prefer if it was possible if the name could be arbitrary (like when using the make -f parameter). However, that said, 95% of the use cases would be covered by a fixed `Makefile`.

**Comment by lmcmicu** [comment]
Ok will make it arbitrary then. Thanks.

**Comment by lmcmicu** [comment]
Something needs to be clarified. Sorry I didn't notice this yesterday. Does the location of views, cgi scripts, and so on still need to be relative to the main workspace dir? Or should those now be relative the the makefile's directory? I believe that the latter is actually simpler (i.e., basically make everything relative to where the configured makefile is). If we need to keep track of *both* the workspace dir and the makefile dir, then this is actually going to introduce a fair amount of complexity.

**Comment by lmcmicu** [comment]
Ignore my last comment for now. I need to continue to think about it. I will send an updated comment that is a bit more clear a little later.

**Comment by lmcmicu** [comment]
Ok, yes, my original comment makes it sounds like a starker choice than it really is :-)

The point is just that if you are using a Makefile in a different directory, then it is not just that the `make` commands (i.e., "actions") must be run relative to that directory, it is also that all of the views and cgi scripts need to be relative to the makefile's directory.

E.g., when you run `make update`, if one of the outcomes is to create a `build/` directory with views and scripts relative to the makefile's directory, then the links in the workflow to those views and scripts should point to the versions in the custom directory, not to the default directory (unless they explicitly contain "../../" in the path).

As far as I am concerned this is totally intuitive, but I was slightly confused because only actions are mentioned in the issue description above ("and to run Make tasks from that Makefile from that directory").

So the upshot is I think it is fine.

**Comment by matentzn** [comment]
Yeah I have not thought that through so far :) my sense would be that Makefile directory = working directory, also for cgi scripts.
